'''
/////////////////////////////////////////////////////
-----------------------------------------------------
By: Enimil Isaac Obo
Mail: isaacoboenimil@gmail.com
linkedIn:linkedin.com/in/isaac-obo-enimil-2a2354223
-----------------------------------------------------
/////////////////////////////////////////////////////
'''
"""
//////////////////////////////////////////////////////////////////////
----------------------------------------------------------------------
 This function is used to generate a specified number of prime numbers
----------------------------------------------------------------------
//////////////////////////////////////////////////////////////////////
"""


# defining the prime_generator function
def prime_generator(number):
    list_of_prime = []

# iterating through the sequence that will be generated by the range function
    for test_factor in range(2, number + 1):
        number_of_factors= 0
        for divisor in range(1, test_factor + 1):


 # Checking if test_factor satisfy the conditions of a prime number
            if test_factor % divisor == 0:
                number_of_factors += 1
        if number_of_factors == 2:
            list_of_prime.append(test_factor)
    return list_of_prime



